# **DataFrame**

In [ ]:
import pandas as pd
import numpy as np

DataFrame es una estructura de datos bidimensional

Se puede considerar una tabla SQL o hoja de calculo en Excel

Un arreglo tiene datos homogeneos, un DataFrame no tiene porque limitarse a datos homogeneos. Son homogeneos solo en las columnas.

pd.DataFrame(), DataFrame inicia con mayuscula por ser una clase

In [ ]:
df = pd.DataFrame({
    'nomb':['Ana',"Maria", 'Jose', 'Luis', 'Aldo', 'Rogelio'],
    'calif':[10,8,8,9,7,5],
    'car':['ISC','ISC','INF','IA','MEC','MEC']
})

In [ ]:
df.dtypes

nomb     object
calif     int64
car      object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   nomb    6 non-null      object
 1   calif   6 non-null      int64
 2   car     6 non-null      object
dtypes: int64(1), object(2)
memory usage: 276.0+ bytes

In [ ]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [ ]:
df.columns

Index(['nomb', 'calif', 'car'], dtype='object')

In [ ]:
df.head()

    nomb  calif  car
0    Ana     10  ISC
1  Maria      8  ISC
2   Jose      8  INF
3   Luis      9   IA
4   Aldo      7  MEC

In [ ]:
df.head(3)

    nomb  calif  car
0    Ana     10  ISC
1  Maria      8  ISC
2   Jose      8  INF

In [ ]:
df.tail()

      nomb  calif  car
1    Maria      8  ISC
2     Jose      8  INF
3     Luis      9   IA
4     Aldo      7  MEC
5  Rogelio      5  MEC

In [ ]:
df.tail(3)

      nomb  calif  car
3     Luis      9   IA
4     Aldo      7  MEC
5  Rogelio      5  MEC

In [ ]:
df.describe()

           calif
count   6.000000
mean    7.833333
std     1.722401
min     5.000000
25%     7.250000
50%     8.000000
75%     8.750000
max    10.000000

In [ ]:
df.mode()

      nomb  calif  car
0     Aldo    8.0  ISC
1      Ana    NaN  MEC
2     Jose    NaN  NaN
3     Luis    NaN  NaN
4    Maria    NaN  NaN
5  Rogelio    NaN  NaN

In [ ]:
df['calif'].mode()

0    8
Name: calif, dtype: int64

In [ ]:
df['calif2'] = [8,7,7,9,7,10]

In [ ]:
df

      nomb  calif  car  calif2
0      Ana     10  ISC       8
1    Maria      8  ISC       7
2     Jose      8  INF       7
3     Luis      9   IA       9
4     Aldo      7  MEC       7
5  Rogelio      5  MEC      10

In [ ]:
df['promedio'] = (df['calif'] +  df['calif2'])/2
df

      nomb  calif  car  calif2  promedio
0      Ana     10  ISC       8       9.0
1    Maria      8  ISC       7       7.5
2     Jose      8  INF       7       7.5
3     Luis      9   IA       9       9.0
4     Aldo      7  MEC       7       7.0
5  Rogelio      5  MEC      10       7.5

In [ ]:
df['calif3'] =[10.8,7,7,8]

ValueError: Length of values (4) does not match length of index (6)

In [ ]:
df.isna()

    nomb  calif    car  calif2  promedio
0  False  False  False   False     False
1  False  False  False   False     False
2  False  False  False   False     False
3  False  False  False   False     False
4  False  False  False   False     False
5  False  False  False   False     False

In [ ]:
df.isna().sum()

nomb        0
calif       0
car         0
calif2      0
promedio    0
dtype: int64

drop.na('culumna')

In [ ]:
dfnew = df.dropna('vslkd')

TypeError: DataFrame.dropna() takes 1 positional argument but 2 were given

In [ ]:
medium = pd['calif'].medium()

TypeError: 'module' object is not subscriptable

In [ ]:
dfsa = df.dropna()
dfsa

      nomb  calif  car  calif2  promedio
0      Ana     10  ISC       8       9.0
1    Maria      8  ISC       7       7.5
2     Jose      8  INF       7       7.5
3     Luis      9   IA       9       9.0
4     Aldo      7  MEC       7       7.0
5  Rogelio      5  MEC      10       7.5

In [ ]:
df['calif'].strna().sum()

AttributeError: 'Series' object has no attribute 'strna'

In [ ]:
mediana = df['calif2'].median()
df2 = df['calif2'].fillna(mediana,inplace=True)
df2

/tmp/ipykernel_258/2005623552.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2 = df['calif2'].fillna(mediana,inplace=True)

In [ ]:
df

      nomb  calif  car  calif2  promedio
0      Ana     10  ISC       8       9.0
1    Maria      8  ISC       7       7.5
2     Jose      8  INF       7       7.5
3     Luis      9   IA       9       9.0
4     Aldo      7  MEC       7       7.0
5  Rogelio      5  MEC      10       7.5

In [ ]:
df3 = pd.DataFrame(
    np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), columns=["a", "b", "c"]
)
df3

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
df3.loc()

In [ ]:
df.loc['a2':'a5', 'calif2']

/usr/local/lib/python3.12/dist-packages/pandas/core/dtypes/common.py:1645: DeprecationWarning: Data type alias 'a' was deprecated in NumPy 2.0. Use the 'S' alias instead.
  npdtype = np.dtype(dtype)
/usr/local/lib/python3.12/dist-packages/pandas/core/dtypes/common.py:1645: DeprecationWarning: Data type alias 'a' was deprecated in NumPy 2.0. Use the 'S' alias instead.
  npdtype = np.dtype(dtype)
/usr/local/lib/python3.12/dist-packages/pandas/core/dtypes/common.py:1645: DeprecationWarning: Data type alias 'a' was deprecated in NumPy 2.0. Use the 'S' alias instead.
  npdtype = np.dtype(dtype)
/usr/local/lib/python3.12/dist-packages/pandas/core/dtypes/common.py:1645: DeprecationWarning: Data type alias 'a' was deprecated in NumPy 2.0. Use the 'S' alias instead.
  npdtype = np.dtype(dtype)

Series([], Name: calif2, dtype: int64)

In [ ]:
df3 = pd.DataFrame(df, index=['a1','a2','a3','a4','a5'])

In [ ]:
df3

   nomb  calif  car  calif2  promedio
a1  NaN    NaN  NaN     NaN       NaN
a2  NaN    NaN  NaN     NaN       NaN
a3  NaN    NaN  NaN     NaN       NaN
a4  NaN    NaN  NaN     NaN       NaN
a5  NaN    NaN  NaN     NaN       NaN

In [ ]:
df3.at['a3','promedio']

np.float64(nan)

In [ ]:
df.iloc[1:4]

    nomb  calif  car  calif2  promedio
1  Maria      8  ISC       7       7.5
2   Jose      8  INF       7       7.5
3   Luis      9   IA       9       9.0

# Clase de 11 de Marzo de 2026

In [ ]:
df.index
#imprime los indices

RangeIndex(start=0, stop=6, step=1)

In [ ]:
df.columns
#imprime las columnas

In [ ]:
df.index['a','b','c']

In [ ]:
df.index['a','b','c','d','e','f','g']

In [ ]:
df.set_index("columna",inplace=True)

In [ ]:
df.set_index("calif",inplace=True)

In [ ]:
df

In [ ]:
df.reset_index(inplace=True)

In [ ]:
df

In [ ]:
datos = {
    'a':[1,2,3],
    'b':[4,5,6]
}
datos

In [ ]:
df = pd.DataFrame(datos,index = ['uno','dos','tres'])
df

In [ ]:
df1 = df.copy()
df2 = df.T
dfUnion = (df1,df2)
dfUnion

(      nomb  calif  car  calif2  promedio
 0      Ana     10  ISC       8       9.0
 1    Maria      8  ISC       7       7.5
 2     Jose      8  INF       7       7.5
 3     Luis      9   IA       9       9.0
 4     Aldo      7  MEC       7       7.0
 5  Rogelio      5  MEC      10       7.5,
             0      1     2     3     4        5
 nomb      Ana  Maria  Jose  Luis  Aldo  Rogelio
 calif      10      8     8     9     7        5
 car       ISC    ISC   INF    IA   MEC      MEC
 calif2      8      7     7     9     7       10
 promedio  9.0    7.5   7.5   9.0   7.0      7.5)

#Clase Viernes 13 de Marzo de 2026