In [1]:
import pandas as pd
import numpy as np

#Inspeccionar

In [4]:
df=pd.read_csv('data.csv')
df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [5]:
df.head(10)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0
5        60    102       127     300.0
6        60    110       136     374.0
7        45    104       134     253.3
8        30    109       133     195.1
9        60     98       124     269.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  169 non-null    int64
 1   Pulse     169 non-null    int64
 2   Maxpulse  169 non-null    int64
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB

In [8]:
df.dtypes

Duration      int64
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

In [9]:
df.shape
#(registros o elementos, columnas)

(169, 4)

In [11]:
df.describe()

         Duration       Pulse    Maxpulse     Calories
count  169.000000  169.000000  169.000000   164.000000
mean    63.846154  107.461538  134.047337   375.790244
std     42.299949   14.510259   16.450434   266.379919
min     15.000000   80.000000  100.000000    50.300000
25%     45.000000  100.000000  124.000000   250.925000
50%     60.000000  105.000000  131.000000   318.600000
75%     60.000000  111.000000  141.000000   387.600000
max    300.000000  159.000000  184.000000  1860.400000

In [17]:
df.isna()

     Duration  Pulse  Maxpulse  Calories
0       False  False     False     False
1       False  False     False     False
2       False  False     False     False
3       False  False     False     False
4       False  False     False     False
..        ...    ...       ...       ...
164     False  False     False     False
165     False  False     False     False
166     False  False     False     False
167     False  False     False     False
168     False  False     False     False

[169 rows x 4 columns]

In [18]:
df.isna().sum()

Duration    0
Pulse       0
Maxpulse    0
Calories    5
dtype: int64

In [12]:
df.isnull().sum()

Duration    0
Pulse       0
Maxpulse    0
Calories    5
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(7)

In [16]:
df["Calories"].duplicated().to_string()

'0      False\n1      False\n2      False\n3      False\n4      False\n5      False\n6      False\n7      False\n8      False\n9      False\n10     False\n11     False\n12     False\n13     False\n14     False\n15     False\n16      True\n17     False\n18     False\n19     False\n20     False\n21     False\n22      True\n23     False\n24     False\n25     False\n26     False\n27      True\n28     False\n29     False\n30      True\n31     False\n32     False\n33     False\n34     False\n35     False\n36      True\n37      True\n38      True\n39     False\n40      True\n41     False\n42     False\n43     False\n44     False\n45     False\n46     False\n47      True\n48     False\n49     False\n50     False\n51     False\n52     False\n53     False\n54     False\n55     False\n56     False\n57     False\n58     False\n59     False\n60     False\n61     False\n62     False\n63     False\n64     False\n65     False\n66     False\n67     False\n68     False\n69     False\n70     False\n71      True\n72     False\n73     False\n74     False\n75     False\n76     False\n77      True\n78     False\n79     False\n80     False\n81     False\n82     False\n83     False\n84     False\n85      True\n86     False\n87     False\n88     False\n89     False\n90     False\n91      True\n92     False\n93     False\n94     False\n95     False\n96     False\n97     False\n98     False\n99     False\n100    False\n101     True\n102     True\n103     True\n104    False\n105    False\n106    False\n107    False\n108    False\n109    False\n110    False\n111     True\n112    False\n113     True\n114    False\n115    False\n116    False\n117    False\n118     True\n119    False\n120    False\n121    False\n122    False\n123    False\n124    False\n125    False\n126    False\n127    False\n128    False\n129    False\n130    False\n131    False\n132    False\n133    False\n134    False\n135    False\n136    False\n137    False\n138    False\n139    False\n140    False\n141     True\n142    False\n143    False\n144    False\n145    False\n146     True\n147    False\n148    False\n149    False\n150    False\n151    False\n152     True\n153    False\n154    False\n155     True\n156    False\n157     True\n158    False\n159    False\n160     True\n161    False\n162    False\n163    False\n164    False\n165     True\n166    False\n167    False\n168    False'

In [30]:
df['Calories'].unique()

array([ 409.1,  479. ,  340. ,  282.4,  406. ,  300. ,  374. ,  253.3,
        195.1,  269. ,  329.3,  250.7,  345.3,  379.3,  275. ,  215.2,
          nan,  323. ,  243. ,  364.2,  282. ,  246. ,  334.5,  250. ,
        241. ,  280. ,  380.3,  180.1,  299. ,  223. ,  361. ,  415. ,
        266. ,  286. ,  329.4,  400. ,  397. ,  273. ,  387.6,  298. ,
        397.6,  380.2,  643.1,  263. ,  486. ,  238. ,  450.7,  413. ,
        305. ,  226.4,  321. , 1376. , 1034.4,  853. ,  341. ,  131.4,
        800.4,  873.4,  816. ,  110.4, 1500.2, 1115. ,  700. ,  953.2,
        304. ,  563.2,  251. ,  500.4, 1729. ,  319.2,  344. ,  151.1,
        500. ,  225.3,  234. , 1000.1,  242. ,   50.3,  600.1,  105.3,
         50.5,  127.4,  229.4,  128.2,  244.2,  188.2,  604.1,   77.7,
         92.7,  124. ,  800.3,   86.2,  500.3, 1860.4,  325.2,  124.2,
        367.6,  351.7,  443. ,  277.4,  332.7,  193.9,  100.7,  336.7,
        344.9,  368.5,  271. ,  275.3,  382. ,  466.4,  384. ,  342.5,
        357.5,  335. ,  327.5,  339. ,  189. ,  317.7,  318. ,  308. ,
        222.4,  390. ,  250.4,  335.4,  470.2,  270.8,  361.9,  185. ,
        409.4,  343. ,  353.2,  275.8,  328. ,  270.4,  382.8,  240.9,
        260.4,  270. ,  280.9,  290.8,  310.2,  320.4,  330.4])

# Limpieza

In [19]:
dfLimpio = df.drop_duplicates()
dfLimpio

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[162 rows x 4 columns]

In [20]:
dfLimpio.duplicated().to_string()

'0      False\n1      False\n2      False\n3      False\n4      False\n5      False\n6      False\n7      False\n8      False\n9      False\n10     False\n11     False\n12     False\n13     False\n14     False\n15     False\n16     False\n17     False\n18     False\n19     False\n20     False\n21     False\n22     False\n23     False\n24     False\n25     False\n26     False\n27     False\n28     False\n29     False\n30     False\n31     False\n32     False\n33     False\n34     False\n35     False\n39     False\n41     False\n42     False\n43     False\n44     False\n45     False\n46     False\n47     False\n48     False\n49     False\n50     False\n51     False\n52     False\n53     False\n54     False\n55     False\n56     False\n57     False\n58     False\n59     False\n60     False\n61     False\n62     False\n63     False\n64     False\n65     False\n66     False\n67     False\n68     False\n69     False\n70     False\n72     False\n73     False\n74     False\n75     False\n76     False\n77     False\n78     False\n79     False\n80     False\n81     False\n82     False\n83     False\n84     False\n85     False\n86     False\n87     False\n88     False\n89     False\n90     False\n91     False\n92     False\n93     False\n94     False\n95     False\n96     False\n97     False\n98     False\n99     False\n100    False\n101    False\n102    False\n103    False\n104    False\n105    False\n106    False\n107    False\n108    False\n109    False\n110    False\n111    False\n112    False\n114    False\n115    False\n116    False\n117    False\n118    False\n119    False\n120    False\n121    False\n122    False\n123    False\n124    False\n125    False\n126    False\n127    False\n128    False\n129    False\n130    False\n131    False\n132    False\n133    False\n134    False\n135    False\n136    False\n137    False\n138    False\n139    False\n140    False\n141    False\n142    False\n143    False\n144    False\n145    False\n146    False\n147    False\n148    False\n149    False\n150    False\n151    False\n152    False\n153    False\n154    False\n156    False\n157    False\n158    False\n159    False\n160    False\n161    False\n162    False\n163    False\n164    False\n165    False\n166    False\n167    False\n168    False'

In [21]:
dfLimpio.isnull().sum()

Duration    0
Pulse       0
Maxpulse    0
Calories    5
dtype: int64

A partir de aca se pueden borrar los datos nulos o rellenarlos

In [23]:
x = dfLimpio.dropna()
x

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[157 rows x 4 columns]

In [24]:
x = dfLimpio.fillna(0)
x

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[162 rows x 4 columns]

In [26]:
x = dfLimpio.fillna(dfLimpio['Calories'].mean())
x

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[162 rows x 4 columns]

In [27]:
x.isna().sum()

Duration    0
Pulse       0
Maxpulse    0
Calories    0
dtype: int64

In [28]:
dfLimpio.isnull().sum()

Duration    0
Pulse       0
Maxpulse    0
Calories    5
dtype: int64