In [49]:
import numpy as np
import pandas as pd

In [17]:
s = pd.Series([10,8,9,9,7])
s

0    10
1     8
2     9
3     9
4     7
dtype: int64

In [4]:
s1 = pd.Series([10,8,9,9,7], ["Ana", "Juan", "Narciso", "Marcela", "Idelfonso"])
s1

Ana          10
Juan          8
Narciso       9
Marcela       9
Idelfonso     7
dtype: int64

In [5]:
s.shape

(5,)

In [6]:
s1.shape

(5,)

In [7]:
type(s)

pandas.core.series.Series

In [8]:
s.dtype

dtype('int64')

In [9]:
s.max()

10

In [10]:
s.min()

7

In [11]:
s.sum()

np.int64(43)

In [12]:
s.mean()

np.float64(8.6)

In [13]:
s.median()

9.0

In [14]:
s.mode()

0    9
dtype: int64

In [15]:
s.std()

1.1401754250991378

In [18]:
s.corr()

TypeError: Series.corr() missing 1 required positional argument: 'other'

In [19]:
s.head()

0    10
1     8
2     9
3     9
4     7
dtype: int64

In [20]:
s1.head()

Ana          10
Juan          8
Narciso       9
Marcela       9
Idelfonso     7
dtype: int64

In [21]:
s1.tail()

Ana          10
Juan          8
Narciso       9
Marcela       9
Idelfonso     7
dtype: int64

In [22]:
s1.Juan

np.int64(8)

In [23]:
s1["Juan"]

np.int64(8)

In [24]:
s1.iloc(0)

In [25]:
s1.iloc([0,2,4])

TypeError: unhashable type: 'list'

In [26]:
s1.loc(0)

In [27]:
s1 > 8.0

Ana           True
Juan         False
Narciso       True
Marcela       True
Idelfonso    False
dtype: bool

In [28]:
s1[s1 > 8]

Ana        10
Narciso     9
Marcela     9
dtype: int64

In [29]:
s1.to_numpy()

array([10,  8,  9,  9,  7])

In [30]:
s1["Romualdo"] = 10
s1

Ana          10
Juan          8
Narciso       9
Marcela       9
Idelfonso     7
Romualdo     10
dtype: int64

In [31]:
"Ana" in s1

True

In [32]:
if (not("Ana" in s1)):
  s1["Ana"] = 9

s1

Ana          10
Juan          8
Narciso       9
Marcela       9
Idelfonso     7
Romualdo     10
dtype: int64

In [37]:
s1.get("Eutanasio")

In [34]:
s.get("Eutanasio", np.nan)

nan

In [35]:
cdif = {"Ana": 10, "Juan":8, "Alfredo":9}
s=pd.Series(cdif)
s

Ana        10
Juan        8
Alfredo     9
dtype: int64

In [38]:
datos = {"Alumnos" : ["Ana", "Juan", "Alfredo", "Romualdo", "Eufrasia"],
         "Calificaciones" : [10,8,9,9,7]}
df = pd.DataFrame(datos)
df

    Alumnos  Calificaciones
0       Ana              10
1      Juan               8
2   Alfredo               9
3  Romualdo               9
4  Eufrasia               7

In [39]:
df.shape

(5, 2)

In [40]:
df.dtypes

Alumnos           object
Calificaciones     int64
dtype: object

In [43]:
df["Carreras"] = ["ISC", "INF", "MEC", "ISC", "IIA"]
df

    Alumnos  Calificaciones Carreras
0       Ana              10      ISC
1      Juan               8      INF
2   Alfredo               9      MEC
3  Romualdo               9      ISC
4  Eufrasia               7      IIA

pd.Series(datos,index=indices,dtype=tipo)

s=pd.Series(datos, name="Nombre")

pd.Series.rename("Nuevo nombre")

In [44]:
s.var()

1.0

In [45]:
s.count()

np.int64(3)

In [46]:
s.cumsum()

Ana        10
Juan       18
Alfredo    27
dtype: int64

In [47]:
s.value_counts()

10    1
8     1
9     1
Name: count, dtype: int64

In [48]:
s.describe()

count     3.0
mean      9.0
std       1.0
min       8.0
25%       8.5
50%       9.0
75%       9.5
max      10.0
dtype: float64

In [54]:
sNum = pd.Series(10, index=['a','b','c','d'])
sNum

a    10
b    10
c    10
d    10
dtype: int64

In [51]:
s2 = pd.Series([10,8,9,9,7], ["Ana", "Juan", "Narciso", "Marcela", "Idelfonso"])
s2

Ana          10
Juan          8
Narciso       9
Marcela       9
Idelfonso     7
dtype: int64

In [52]:
s3 = pd.Series(s2,index=["Ana", "Juan","Carlos"])
s3

Ana       10.0
Juan       8.0
Carlos     NaN
dtype: float64

In [55]:
s.sort_values()

Juan        8
Alfredo     9
Ana        10
dtype: int64

In [57]:
s.sort_index()

Alfredo     9
Ana        10
Juan        8
dtype: int64

In [ ]:
s.apply(funcion)

In [59]:
sc = pd.Series(["Juan", "Maria", "Rosa"])
sc

0     Juan
1    Maria
2     Rosa
dtype: object

In [63]:
sm = s.apply(str.upper)

TypeError: descriptor 'upper' for 'str' objects doesn't apply to a 'int' object

In [64]:
s4 = pd.Series([1,7,7,8,10], index = ['a','b','c','d'])
s4

ValueError: Length of values (5) does not match length of index (4)

In [65]:
s5 = pd.Series(s4,index=['a','c','e'])

NameError: name 's4' is not defined

In [66]:
s5['d'] = 8
s5

NameError: name 's5' is not defined

In [67]:
s.dropna()
s

Ana        10
Juan        8
Alfredo     9
dtype: int64

In [68]:
s6=pd.Series(['a','b','c','d'])
s6.sum()

'abcd'